### ISSUE TITLE
A few feature requests and a minor bug

### ISSUE THREAD

**Issue by Toonerz** [Olivercomet/EPFExplorer#12]
Currently, to export XM files, one needs to do them all one by one. A button to export all would be nice.

(these next two might be for @MCJack123 to look into)

Vibrato seems to be a bit slower than it should be (see Gadget Room).

Reducing the file size of the XM's to only have the samples needed, would be nice. (Jack has told me this would need a decent bit of rewritten code or added code, however, so, not sure how viable this is).

**Comment by Olivercomet** [comment]
I have added your first request in release v0.9.1.

**Comment by Toonerz** [comment]
Closing this. All except for the bottom thing have been added. Jack says he will write a seperate program, just for removing unneeded samples, based off work on Unkrawerter.
