### ISSUE TITLE
Newer revisions for the game have missing files

### ISSUE THREAD

**Issue by PHandlerC** [Olivercomet/EPFExplorer#25]
While the game was exported with each market in mind, 2 revisions to the US version added Spanish and French support, respectively. The problem is that the program is not detecting the folders in which the additional assets are.

All the MPB files inside fs.arc/levels are in Spanish in Revision 1 and in French in Revision 2.
Curiously, Revision 2 detects an additional Spanish folder inside the levels folder, but not an English one.

**Comment by Olivercomet** [comment]
Try the new release? It should show the multilanguage /levels/ folders (including English) on rev2 - let me know if it works for you.

**Comment by PHandlerC** [comment]
Yes, it's now working properly on both revisions!! Thank you so much for pushing a fix this quickly!! Have a good day!!

**Comment by PHandlerC** [comment]
Ah, sorry for re-opening this ticket, but it also seems the same applies to files inside the fs.arc. In the "bg" folder, titlescreens for the minigames also have other language variants which EPFExplorer is not picking up

**Comment by Olivercomet** [comment]
Sure, I can probably look into this soon.

**Comment by Olivercomet** [comment]
Try now? The files you mentioned (and others) are now appearing on the new release.

**Comment by PHandlerC** [comment]
Hello. Sorry for the late reply, but it seems to be working perfectly! Thank you very much!
