### ISSUE TITLE
Incorrect tileset/tilemap generation

### ISSUE THREAD

**Issue by PHandlerC** [Olivercomet/EPFExplorer#26]
I've been trying to use the tool to make a Portuguese version of EPF DS, but it seems there's a problem with the tilemap/tileset generation.

Since most rooms are just the PSA Missions rooms, but compressed, I decided to render the Portuguese assets for some rooms and re-added them to the levels/tileset folders inside the fs.arc file. I exported a PNG from the MPB/TSB Editor, edited the image and imported them back to game.

However, the game had some issues with the transparent color (the editor warns that the game expects a bright magenta color for transparency). The game decided to make the first color generated by the editor as the transparent color. This is how the Coffee Shop looked like in the editor
![image](https://github.com/user-attachments/assets/741614da-88f1-49e5-a151-734230506ffb)

but this is how it looked in-game:
![TESTEDIT](https://github.com/user-attachments/assets/ac4aedb1-a1e7-41e4-9e4f-006633665bad)

(Screenshots taken using the DeSmuME emulator, but I also checked on real hardware and the problem persists)

The same problem happened when I tried the same method to replace the Town and the Plaza, however, I was able to mitigate the problem to some extent by adding the FF00FF color directly on the first pixels of the files. Since the HUD hides these spots on external areas, they are not visible on screen, however they are visible on indoor areas, which can be scrolled infinitely.

(Disabling the HUD on DeSmuME shows that the first 8x8 tile for the rooms is still transparent)

![TESTV2__14657](https://github.com/user-attachments/assets/6a234e9a-3865-4cc8-a390-e98da569c25d)
![TESTV2__30714](https://github.com/user-attachments/assets/dc911e83-ad04-42ca-84a8-8e53d97c4b7a)
![TESTV2__9590](https://github.com/user-attachments/assets/f7f9f8dd-a21c-410b-bd9c-14a7728d02e5)

Checking the MPB/TSB on a Hex Editor, it seems the editor is generating them sequentially. They are scrambled on the original files. My guess is that the game is hard coded to always set any tiles with values 00 to be transparent, regardless of them being the intended magenta color or not. This guess comes from the fact that, loading the original English tileset with the edited Portuguese tilemap generated by the Editor, the same spots where the issue occurs show up as magenta in the editor

![Palette](https://github.com/user-attachments/assets/7c452f55-768b-43bf-bcba-429df940c910)

**Comment by Olivercomet** [comment]
Hi, thanks for the detailed report. It should be fixed in the new release (the tile at index 0 is now filled with a boilerplate blank tile so that it doesn't get erroneously assigned to useful parts of the image).

(The coffee shop now successfully generates after being edited:)
![image](https://github.com/user-attachments/assets/e483e800-0505-4f65-b984-32ec6938e0da)

**Comment by PHandlerC** [comment]
Ah, it's working perfectly!! Thank you so much for pushing a fix this fast!! Have a good day!!

**Comment by PHandlerC** [comment]
I'm very sorry to open this issue again, and I will understand if you are not interested in fixing it.

In short, I had some trouble exporting and re-import the file "Smilie" from the Game.rdt. This is because the current UI for EPFExplorer always makes sure you set one palette option for transparency, however this file does not set transparency. You see, the raw file has its dead zone as completely black, but inside its spritesheet, it gets cutout so it appears to have a 1px black outline.

I'm almost sure that the game has a predefined palette that always sets the bright magenta color as the first palette color and as the transparent color, even if the sprite or tileset does not use it. I think this issue could be fixed by making sure the color is added to the palette when no other color is set as the transparent layer

<img width="108" height="78" alt="Image" src="https://github.com/user-attachments/assets/b8185c2a-f093-4a7b-86a8-021e6cb92ea5" />

<img width="118" height="102" alt="Image" src="https://github.com/user-attachments/assets/6387a1ea-e3e3-4a68-a21f-364740aac894" />
