### ISSUE TITLE
Automatic rewrite

### ISSUE THREAD

**Issue by PHandlerC** [Olivercomet/EPFExplorer#27]
While I was trying to find some graphics to be updated for another language in the Game.rdt, some of the graphics in the game got corrupted.

![TESTV2__25823](https://github.com/user-attachments/assets/804274bd-46d8-4872-a7e3-ffac1a6a9dce)

However, I was quickly able to figure out what happened. While browsing inside the Game.rdt, I used the "Open" option to check the sprites and make sure I was replacing the correct ones. However, EPFExplorer automatically had re-saved the sprites and incorrectly atributted different alpha colors to them, like with the Inventory and the main cursor icon.

It seems that when using the "Open" option, it will always set a default alpha color to sprites, normally black, even if the sprite originally never had transparency, like with the background for the Spy Gadget, game's borders black outline and the "Thank you" postcard splash you receive when finishing optional missions.

**Comment by Olivercomet** [comment]
Hmm, thanks for letting me know, though this might be a bit more difficult
to fix than the other bugs you've recently found. I would not expect a fix
in the near future unfortunately.

**Comment by PHandlerC** [comment]
Ah, I absolutely understand. Even so, thank you very much for taking a look at all the bugs I pointed out in the last few days!!
