### ISSUE TITLE
Question About the extracted .sequence files from music.bin

### ISSUE THREAD

**Issue by Winonamac** [Olivercomet/EPFExplorer#5]
Hey! I found your tool after doing some searching on Github. NGL this tool is really good so far, but I have a question about the .sequence files. What audio format do they use? I tried importing the files into Audacity as raw data with different settings but haven't got anything that sounds like normal audio. I tried opening them with HxD to check the file header but each file had a different header. So either some of the files use different audio formats or they all use a headerless audio format. I'm planning on using SoX to try out different audio formats that the files might use but if you know what audio format they use please let me know!

Thanks!
-Winonamac

(lmao I wrote that like I'm writing an email)

P.S. While looking on Github I found this attempt at [Reverse Engineering the Club Penguin Games](https://github.com/wertercatt/Reverse-Engineering-Club-Penguin-DS-Games) I'll link it here in case it might help you.

**Comment by Olivercomet** [comment]
They are still in the game's own sequenced music format, no program can
open them.

I last had a look a year ago so I'm a bit rusty, but they have a header
with things like BPM and which patterns to follow. I did manage to edit the
song itself but only as far as messing it up - I don't know the specifics
of what the the 'play note' command is etc. It seems it might be some bit
wise thing?

It also seems like there might be a superficial similarity to XM files
(which are what the composer used in his composing software). My other
feeling is that they might be based on Nintendo's DS sequence format, as
all the other formats in EPF seem tailored to the system, and this one is
probably no exception.

I may have a look in a couple of days to see if I can make any sense of it
this time. If you find anything please let me know! :)

**Comment by Olivercomet** [comment]
Music sequences now extract as .XM, albeit lacking samples

**Comment by Olivercomet** [comment]
Music sequences now extract as .XM, albeit lacking samples
